# Generated by Django 3.0 on 2019-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
